{
 "title": "Image Scraper Job",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "jobname", "label": "Job Name", "query": { "query": "label_values(job_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Rates Items/s",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job_name, status) (rate(jobbernetes_job_processed_total{job_name=~\"${jobname}\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Successfull",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job_name, status) (increase(jobbernetes_job_processed_total{status=\"success\", job_name=~\"${jobname}\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Total Started",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job_name, status) (increase(jobbernetes_job_started_total{job_name=~\"${jobname}\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Total Failed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job_name, status) (increase(jobbernetes_job_processed_total{status=\"fail\", job_name=~\"${jobname}\"}[${__range_s}s]))"
    }
   ]
  },
  {
   "title": "Exceptions Only",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{jobbernetes_job_name=~\"${jobname}\"} |~ \"Exception|ERR\""
    }
   ]
  },
  {
   "title": "All Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{jobbernetes_job_name=~\"${jobname}\"}"
    }
   ]
  }
 ]
}