nodeExporter:
  enabled: false

  ## node-exporter resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi


alertmanager:
  enabled: false

  ## alertmanager resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi

  persistentVolume:
    enabled: true
    existingClaim: prometheus-alertmanager-pvc

  ## Security context to be added to alertmanager pods
  ##
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    runAsGroup: 1000
    fsGroup: 1000

server:
  enabled: true

  remoteWrite:
    - url: http://influxdb:8086/api/v1/prom/write?db=jobbernetes-prometheus

  remoteRead:
    - url: http://influxdb:8086/api/v1/prom/read?db=jobbernetes-prometheus

  persistentVolume:
    enabled: true
    existingClaim: prometheus-server-pvc

  ## Security context to be added to server pods
  ##
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    runAsGroup: 1000
    fsGroup: 1000

  ## Prometheus server resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      memory: 768Mi
      cpu: 1
    limits:
      memory: 1280Mi
      cpu: 3

pushgateway:
  # we use prom-aggregation-gateway instead
  # see: https://github.com/weaveworks/prom-aggregation-gateway
  enabled: false

  ## Security context to be added to push-gateway pods
  ##
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true

  ## pushgateway resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 2
      memory: 256Mi
    requests:
      cpu: 0.2
      memory: 128Mi

  persistentVolume:
    enabled: false
    existingClaim: prometheus-pushgateway-pvc
