nodeExporter:
  enabled: false

  ## node-exporter resource limits & requests
  ## Ref: https://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 30Mi


alertmanager:
  enabled: false

  ## alertmanager resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 10m
      memory: 32Mi
    requests:
      cpu: 10m
      memory: 32Mi

  persistentVolume:
    enabled: true
    existingClaim: prometheus-alertmanager-pvc

  ## Security context to be added to alertmanager pods
  ##
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    runAsGroup: 1000
    fsGroup: 1000

server:
  enabled: true

  remoteWrite:
      - url: http://victoria-metrics-single-server:8428/api/v1/write
        queue_config:
          max_samples_per_send: 10000
          capacity: 20000
          max_shards: 30

  persistentVolume:
    enabled: true
    existingClaim: prometheus-server-pvc

  ## Security context to be added to server pods
  ##
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
    runAsGroup: 1000
    fsGroup: 1000

  ## Prometheus server resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      memory: 1768Mi
      cpu: 200m
    limits:
      memory: 2768Mi
      cpu: 500m

pushgateway:
  # we use prom-aggregation-gateway instead
  # see: https://github.com/weaveworks/prom-aggregation-gateway
  enabled: false

  ## Security context to be added to push-gateway pods
  ##
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true

  ## pushgateway resource requests and limits
  ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 128Mi

  persistentVolume:
    enabled: false
    existingClaim: prometheus-pushgateway-pvc
