apiVersion: k3d.io/v1alpha2
kind: Simple

servers: 1
agents: 2

kubeAPI:
    hostIP: "127.0.0.1"
    hostPort: "6445"

ports:
    # HTTP
    - port: 8080:80
      nodeFilters:
          - loadbalancer

    # RabbitMQ (rabbitmq_management)
    - port: 15672:15672
      nodeFilters:
          - loadbalancer
