apiVersion: k3d.io/v1alpha2
kind: Simple

servers: 1
agents: 2

kubeAPI:
    hostIP: "0.0.0.0"
    hostPort: "6445"

ports:
    # HTTP
    - port: 80:80
      nodeFilters:
          - loadbalancer

#    # MongoDB
#    - port: 27017:27017
#      nodeFilters:
#          - loadbalancer

#    # Kafka
#    - port: 9094:9094
#      nodeFilters:
#          - loadbalancer
