apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: djs-volume
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/data/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  storageClassName: djs-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
